# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-16 12:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('other_names', models.CharField(blank=True, max_length=250, null=True, verbose_name='other names')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/avatars', verbose_name='profile picture')),
                ('id_number', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='id_number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='location')),
                ('job_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='job title')),
                ('preonboarding_deadline', models.DateField(blank=True, null=True, verbose_name='preonboarding deadline')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='child name')),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('birth_certificate', models.FileField(null=True, upload_to='accounts/documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=25, null=True, verbose_name='gender')),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=150, null=True)),
                ('national_id', models.FileField(null=True, upload_to='accounts/documents')),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=50, null=True)),
                ('name_of_spouse', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_of_spouse', models.CharField(blank=True, max_length=50, null=True)),
                ('marriage_cert', models.FileField(blank=True, null=True, upload_to='accounts/documents')),
                ('name_of_father', models.CharField(max_length=250, null=True)),
                ('name_of_mother', models.CharField(max_length=250, null=True)),
                ('nok_name', models.CharField(max_length=250, null=True)),
                ('nok_dob', models.DateField(null=True)),
                ('nok_address', models.CharField(max_length=250, null=True)),
                ('nok_contact', models.CharField(max_length=50, null=True)),
                ('educational_cert', models.FileField(null=True, upload_to='accounts/documents')),
                ('professional_body_affiliates', models.FileField(null=True, upload_to='accounts/documents')),
                ('nss_start_date', models.DateField(null=True)),
                ('nss_end_date', models.DateField(null=True)),
                ('nss_cert', models.FileField(null=True, upload_to='accounts/documents')),
                ('res_physical_address', models.CharField(max_length=250, null=True, verbose_name='residential address (physical)')),
                ('res_digital_address', models.CharField(max_length=250, null=True, verbose_name='residential address (digital)')),
                ('res_phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='residential phone number')),
                ('postal_address', models.CharField(blank=True, max_length=250, null=True)),
                ('ssnit_number', models.CharField(max_length=50, null=True, verbose_name='social security number')),
                ('tin_number', models.CharField(max_length=50, null=True)),
                ('bank_account_number', models.CharField(max_length=50, null=True)),
                ('bank_branch', models.CharField(max_length=150, null=True)),
                ('bank_name', models.CharField(max_length=150, null=True)),
                ('sort_code', models.CharField(max_length=150, null=True)),
                ('family_beneficiary', models.CharField(max_length=150, null=True)),
                ('relationship_to_beneficiary', models.CharField(max_length=50, null=True)),
                ('beneficiary_phone_number', models.CharField(max_length=50, null=True)),
                ('principal_form', models.FileField(null=True, upload_to='accounts/documents', verbose_name='medical insurance principal form')),
                ('dependant_form', models.FileField(null=True, upload_to='accounts/documents', verbose_name='medical insurance dependant form')),
                ('children', models.ManyToManyField(null=True, to='accounts.Child')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
