# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200117_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=25, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('married', 'married'), ('single', 'single'), ('divorced', 'divorced')], default='single', max_length=50, null=True),
        ),
    ]
