# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200118_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_manager',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='line manager'),
        ),
    ]
