# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-30 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_line_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='children',
        ),
    ]
